os:
  - linux

dist: xenial

language: python

python:
  - "3.8"

services: mysql

before_script:
   - mysql -e 'CREATE DATABASE IF NOT EXISTS flask_capstone_schema;'


script:
  # run tests
  - python -m pytest -v

  # code coverage reports
  - coverage erase
  - coverage run --branch main.py && coverage html

after_success:
  - codecov