"""empty message

Revision ID: 1096526e6a14
Revises: c93540c85c6c
Create Date: 2020-10-02 14:43:04.971989

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1096526e6a14'
down_revision = 'c93540c85c6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('camera', sa.Column('mac_address', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('camera', 'mac_address')
    # ### end Alembic commands ###
