"""empty message

Revision ID: 18d7b6b01e86
Revises: 9c63780e00fc
Create Date: 2020-10-26 21:07:30.721922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18d7b6b01e86'
down_revision = '9c63780e00fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('notes', sa.String(length=1500), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logs', 'notes')
    # ### end Alembic commands ###
