"""empty message

Revision ID: 1b44d943ede8
Revises: 7d6cf8ae66c3
Create Date: 2020-10-15 20:54:36.322769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b44d943ede8'
down_revision = '7d6cf8ae66c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('space_ibfk_1', 'space', type_='foreignkey')
    op.create_foreign_key(None, 'space', 'camera', ['camera_id'], ['id'], ondelete='cascade')
    op.drop_constraint('space_dimensions_ibfk_1', 'space_dimensions', type_='foreignkey')
    op.create_foreign_key(None, 'space_dimensions', 'space', ['space_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'space_dimensions', type_='foreignkey')
    op.create_foreign_key('space_dimensions_ibfk_1', 'space_dimensions', 'space', ['space_id'], ['id'])
    op.drop_constraint(None, 'space', type_='foreignkey')
    op.create_foreign_key('space_ibfk_1', 'space', 'camera', ['camera_id'], ['id'])
    # ### end Alembic commands ###
