"""empty message

Revision ID: 30aff9aae825
Revises: 1b44d943ede8
Create Date: 2020-10-15 21:12:31.423499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30aff9aae825'
down_revision = '1b44d943ede8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('camera_ibfk_1', 'camera', type_='foreignkey')
    op.create_foreign_key(None, 'camera', 'lot', ['lot_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'camera', type_='foreignkey')
    op.create_foreign_key('camera_ibfk_1', 'camera', 'lot', ['lot_id'], ['id'])
    # ### end Alembic commands ###
