"""empty message

Revision ID: 36305abacc83
Revises: b3f87384998e
Create Date: 2020-10-18 17:48:15.742127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36305abacc83'
down_revision = 'b3f87384998e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zone', sa.Column('description', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_zone_description'), 'zone', ['description'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zone_description'), table_name='zone')
    op.drop_column('zone', 'description')
    # ### end Alembic commands ###
