"""empty message

Revision ID: 3692f2b0ee21
Revises: 3bbb274d1a70
Create Date: 2020-09-09 04:19:05.843859

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3692f2b0ee21'
down_revision = '3bbb274d1a70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('space', 'availability')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('space', sa.Column('availability', mysql.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
