"""Adding space_dimensions and control_points tables

Revision ID: 3a380806a196
Revises: c93ddc774886
Create Date: 2020-09-09 23:19:44.040123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a380806a196'
down_revision = 'c93ddc774886'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('control_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_x', sa.Integer(), nullable=True),
    sa.Column('start_y', sa.Integer(), nullable=True),
    sa.Column('end_x', sa.Integer(), nullable=True),
    sa.Column('end_y', sa.Integer(), nullable=True),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['camera.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('space_dimensions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_x', sa.Integer(), nullable=True),
    sa.Column('start_y', sa.Integer(), nullable=True),
    sa.Column('end_x', sa.Integer(), nullable=True),
    sa.Column('end_y', sa.Integer(), nullable=True),
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['space_id'], ['space.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('space_dimensions')
    op.drop_table('control_points')
    # ### end Alembic commands ###
