"""empty message

Revision ID: 3bbb274d1a70
Revises: 0cd3a0e4827f
Create Date: 2020-09-09 04:10:58.048886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bbb274d1a70'
down_revision = '0cd3a0e4827f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('space_ibfk_3', 'space', type_='foreignkey')
    op.drop_constraint('space_ibfk_2', 'space', type_='foreignkey')
    op.create_foreign_key(None, 'space', 'lot', ['lot_id'], ['id'])
    op.create_foreign_key(None, 'space', 'zone', ['zone_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'space', type_='foreignkey')
    op.drop_constraint(None, 'space', type_='foreignkey')
    op.create_foreign_key('space_ibfk_2', 'space', 'lotzone', ['lot_id'], ['lot_id'])
    op.create_foreign_key('space_ibfk_3', 'space', 'lotzone', ['zone_id'], ['zone_id'])
    # ### end Alembic commands ###
