"""empty message

Revision ID: 6f5c85fa96ac
Revises: 8f617154c603
Create Date: 2020-09-10 13:00:48.239482

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6f5c85fa96ac'
down_revision = '8f617154c603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'activate_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('activate_hash', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
