"""empty message

Revision ID: 7bdbfc8db1f4
Revises: ff4514e21a83
Create Date: 2020-10-15 20:13:37.600581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bdbfc8db1f4'
down_revision = 'ff4514e21a83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('type', sa.Enum('WEBSITE', 'DATABASE', 'HARDWARE', name='logtype'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logs', 'type')
    # ### end Alembic commands ###
