"""empty message

Revision ID: 7d6cf8ae66c3
Revises: 7bdbfc8db1f4
Create Date: 2020-10-15 20:45:39.283796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d6cf8ae66c3'
down_revision = '7bdbfc8db1f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('control_points_ibfk_1', 'control_points', type_='foreignkey')
    op.create_foreign_key(None, 'control_points', 'camera', ['camera_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'control_points', type_='foreignkey')
    op.create_foreign_key('control_points_ibfk_1', 'control_points', 'camera', ['camera_id'], ['id'])
    # ### end Alembic commands ###
