"""empty message

Revision ID: 7e7a003df875
Revises: f6aacc7d3ff6
Create Date: 2020-10-21 14:13:18.625919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e7a003df875'
down_revision = 'f6aacc7d3ff6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('updates', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'updates')
    # ### end Alembic commands ###
