"""empty message

Revision ID: 87ed666e5c7d
Revises: 5019f9103281
Create Date: 2020-10-27 07:12:11.423663

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '87ed666e5c7d'
down_revision = '5019f9103281'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'updates')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('updates', mysql.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###
