"""empty message

Revision ID: 8f617154c603
Revises: b7fd4a8eaf6b
Create Date: 2020-09-10 12:06:57.614738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f617154c603'
down_revision = 'b7fd4a8eaf6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('activate_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'activate_hash')
    # ### end Alembic commands ###
