"""Adding admin_groups table

Revision ID: 9065b709ca22
Revises: 3a380806a196
Create Date: 2020-09-09 23:37:43.593689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9065b709ca22'
down_revision = '3a380806a196'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('activate_hash', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('group_id', sa.Integer(), nullable=False))
    # op.create_foreign_key(None, 'user', 'admin_group', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'group_id')
    op.drop_column('user', 'activate_hash')
    op.drop_table('admin_group')
    # ### end Alembic commands ###
