"""empty message

Revision ID: 9c63780e00fc
Revises: 82a19eb46030
Create Date: 2020-10-25 14:09:53.865403

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9c63780e00fc'
down_revision = '82a19eb46030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('middle_initial', sa.String(length=1), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['admin_group.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('first_name', 'last_name', 'middle_initial')
    )
    op.create_index(op.f('ix_administrator_email'), 'administrator', ['email'], unique=True)
    op.create_index(op.f('ix_administrator_first_name'), 'administrator', ['first_name'], unique=False)
    op.create_index(op.f('ix_administrator_last_name'), 'administrator', ['last_name'], unique=False)
    op.create_index(op.f('ix_administrator_middle_initial'), 'administrator', ['middle_initial'], unique=False)
    op.drop_index('first_name', table_name='administrators')
    op.drop_index('ix_administrators_email', table_name='administrators')
    op.drop_index('ix_administrators_first_name', table_name='administrators')
    op.drop_index('ix_administrators_last_name', table_name='administrators')
    op.drop_index('ix_administrators_middle_initial', table_name='administrators')
    op.drop_table('administrators')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrators',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('first_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('middle_initial', mysql.VARCHAR(length=1), nullable=True),
    sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('group_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['admin_group.id'], name='administrators_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_administrators_middle_initial', 'administrators', ['middle_initial'], unique=False)
    op.create_index('ix_administrators_last_name', 'administrators', ['last_name'], unique=False)
    op.create_index('ix_administrators_first_name', 'administrators', ['first_name'], unique=False)
    op.create_index('ix_administrators_email', 'administrators', ['email'], unique=True)
    op.create_index('first_name', 'administrators', ['first_name', 'last_name', 'middle_initial'], unique=True)
    op.drop_index(op.f('ix_administrator_middle_initial'), table_name='administrator')
    op.drop_index(op.f('ix_administrator_last_name'), table_name='administrator')
    op.drop_index(op.f('ix_administrator_first_name'), table_name='administrator')
    op.drop_index(op.f('ix_administrator_email'), table_name='administrator')
    op.drop_table('administrator')
    # ### end Alembic commands ###
