"""empty message

Revision ID: b7fd4a8eaf6b
Revises: f2e1f7847f84
Create Date: 2020-09-10 12:06:45.392331

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b7fd4a8eaf6b'
down_revision = 'f2e1f7847f84'
branch_labels = None
depends_on = None


def upgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('user', 'activate_hash')
    # ### end Alembic commands ###


def downgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('user', sa.Column('activate_hash', mysql.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
