"""empty message

Revision ID: b8be8d56bb73
Revises: 36305abacc83
Create Date: 2020-10-18 17:56:15.081439

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b8be8d56bb73'
down_revision = '36305abacc83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_zone_description', table_name='zone')
    op.drop_column('zone', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zone', sa.Column('description', mysql.VARCHAR(length=100), nullable=True))
    op.create_index('ix_zone_description', 'zone', ['description'], unique=True)
    # ### end Alembic commands ###
