"""empty message

Revision ID: ba46f4c910e3
Revises: 1096526e6a14
Create Date: 2020-10-13 17:44:33.086168

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ba46f4c910e3'
down_revision = '1096526e6a14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('camera', sa.Column('ip_address', sa.String(length=20), nullable=True))
    op.drop_column('camera', 'mac_address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('camera', sa.Column('mac_address', mysql.VARCHAR(length=20), nullable=True))
    op.drop_column('camera', 'ip_address')
    # ### end Alembic commands ###
