"""empty message

Revision ID: c93540c85c6c
Revises: 098ad7dfe4b7
Create Date: 2020-10-02 14:07:24.418987

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c93540c85c6c'
down_revision = '098ad7dfe4b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('control_points', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('control_points', sa.Column('width', sa.Integer(), nullable=True))
    op.drop_column('control_points', 'end_y')
    op.drop_column('control_points', 'end_x')
    op.add_column('space_dimensions', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('space_dimensions', sa.Column('width', sa.Integer(), nullable=True))
    op.drop_column('space_dimensions', 'end_y')
    op.drop_column('space_dimensions', 'end_x')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('space_dimensions', sa.Column('end_x', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('space_dimensions', sa.Column('end_y', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('space_dimensions', 'width')
    op.drop_column('space_dimensions', 'height')
    op.add_column('control_points', sa.Column('end_x', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('control_points', sa.Column('end_y', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('control_points', 'width')
    op.drop_column('control_points', 'height')
    # ### end Alembic commands ###
