"""empty message

Revision ID: c93ddc774886
Revises: 3692f2b0ee21
Create Date: 2020-09-09 04:19:33.958850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c93ddc774886'
down_revision = '3692f2b0ee21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('space', sa.Column('availability', sa.Enum('AVAILABLE', 'NOT_AVAILABLE', 'RESERVED', name='spaceavailability'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('space', 'availability')
    # ### end Alembic commands ###
