"""empty message

Revision ID: f2e1f7847f84
Revises: dd312b304de4
Create Date: 2020-09-10 12:02:05.669534

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f2e1f7847f84'
down_revision = 'dd312b304de4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_zone_description', table_name='zone')
    op.drop_column('zone', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zone', sa.Column('description', mysql.VARCHAR(length=100), nullable=True))
    op.create_index('ix_zone_description', 'zone', ['description'], unique=True)
    # ### end Alembic commands ###
