"""empty message

Revision ID: f6aacc7d3ff6
Revises: 151b17a19dd7
Create Date: 2020-10-20 20:41:57.738944

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f6aacc7d3ff6'
down_revision = '151b17a19dd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'administrator')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('administrator', mysql.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###
