"""empty message

Revision ID: fc3ce30ed348
Revises: 9065b709ca22
Create Date: 2020-09-10 00:40:07.234651

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fc3ce30ed348'
down_revision = '9065b709ca22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'group_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'user', 'admin_group', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.alter_column('user', 'group_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
