"""empty message

Revision ID: ff4514e21a83
Revises: e94681b331ae
Create Date: 2020-10-15 20:12:51.811575

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ff4514e21a83'
down_revision = 'e94681b331ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logs', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('type', mysql.ENUM('WEBSITE', 'DATBASE', 'HARDWARE'), nullable=False))
    # ### end Alembic commands ###
